### ISSUE TITLE
[bug] when fetch error

### ISSUE THREAD

**Issue by lzsheng** [grischaerbe/cacheables#6]
the source code
![wecom-temp-e957d75f5941203482c21b10ad7ca896](https://user-images.githubusercontent.com/8055289/147624418-8ce30109-fafa-44be-ac07-2ab16929de6f.png)

when the resource() error, my code `return Promise.reject()`
source code:  #fetch -> `await this.#promise`   no try...catch.  Causes cache judgment error

**Comment by grischaerbe** [comment]
Hey @lzsheng, sorry for replying so late. I'm not sure what you are trying to say, can you give an example? I'm also open for PRs.

**Comment by kernwig** [comment]
I just immediately hit this bug while trying to use this project for the first time and writing my unit tests. The PR #8 has a unit test that demonstrates the problem.

When the fetch function returns an error, the error is being cached instead of retrying. You can clearly see in the code that there is no error handling on the `await`.

**Comment by grischaerbe** [comment]
Fixed by #8
